"common-tools":
  - .github/**
  - packages/base-cli/**
  - packages/cascade-layer-name-parser/**
  - packages/color-helpers/**
  - packages/css-calc/**
  - packages/css-color-parser/**
  - packages/css-parser-algorithms/**
  - packages/css-tokenizer/**
  - packages/media-query-list-parser/**
  - packages/postcss-tape/**
  - packages/selector-specificity/**
  - plugins/postcss-base-plugin/**
  - rollup/**

"plugin-packs/postcss-preset-env":
  - plugin-packs/postcss-preset-env/**

"cli":
  - cli/csstools-cli/**
  - packages/base-cli/**

"e2e":
  - e2e/**

"experimental":
  - experimental/**

"plugins/css-all-property":
  - plugins/css-all-property/**
  - experimental/css-all-property/**

"plugins/css-blank-pseudo":
  - plugins/css-blank-pseudo/**
  - experimental/css-blank-pseudo/**

"plugins/css-has-pseudo":
  - plugins/css-has-pseudo/**
  - experimental/css-has-pseudo/**

"plugins/css-prefers-color-scheme":
  - plugins/css-prefers-color-scheme/**
  - experimental/css-prefers-color-scheme/**

"plugins/postcss-attribute-case-insensitive":
  - plugins/postcss-attribute-case-insensitive/**
  - experimental/postcss-attribute-case-insensitive/**

"plugins/postcss-cascade-layers":
  - plugins/postcss-cascade-layers/**
  - experimental/postcss-cascade-layers/**

"plugins/postcss-color-function":
  - plugins/postcss-color-function/**
  - experimental/postcss-color-function/**

"plugins/postcss-color-functional-notation":
  - plugins/postcss-color-functional-notation/**
  - experimental/postcss-color-functional-notation/**

"plugins/postcss-color-hex-alpha":
  - plugins/postcss-color-hex-alpha/**
  - experimental/postcss-color-hex-alpha/**

"plugins/postcss-color-rebeccapurple":
  - plugins/postcss-color-rebeccapurple/**
  - experimental/postcss-color-rebeccapurple/**

"plugins/postcss-color-mix-function":
  - plugins/postcss-color-mix-function/**
  - experimental/postcss-color-mix-function/**

"plugins/postcss-conditional-values":
  - plugins/postcss-conditional-values/**
  - experimental/postcss-conditional-values/**

"plugins/postcss-custom-media":
  - plugins/postcss-custom-media/**
  - experimental/postcss-custom-media/**

"plugins/postcss-custom-properties":
  - plugins/postcss-custom-properties/**
  - experimental/postcss-custom-properties/**

"plugins/postcss-custom-selectors":
  - plugins/postcss-custom-selectors/**
  - experimental/postcss-custom-selectors/**

"plugins/postcss-design-tokens":
  - plugins/postcss-design-tokens/**
  - experimental/postcss-design-tokens/**

"plugins/postcss-dir-pseudo-class":
  - plugins/postcss-dir-pseudo-class/**
  - experimental/postcss-dir-pseudo-class/**

"plugins/postcss-double-position-gradients":
  - plugins/postcss-double-position-gradients/**
  - experimental/postcss-double-position-gradients/**

"plugins/postcss-env-function":
  - plugins/postcss-env-function/**
  - experimental/postcss-env-function/**

"plugins/postcss-extract":
  - plugins/postcss-extract/**
  - experimental/postcss-extract/**

"plugins/postcss-focus-visible":
  - plugins/postcss-focus-visible/**
  - experimental/postcss-focus-visible/**

"plugins/postcss-focus-within":
  - plugins/postcss-focus-within/**
  - experimental/postcss-focus-within/**

"plugins/postcss-font-variant":
  - plugins/postcss-font-variant/**
  - experimental/postcss-font-variant/**

"plugins/postcss-font-format-keywords":
  - plugins/postcss-font-format-keywords/**
  - experimental/postcss-font-format-keywords/**

"plugins/postcss-gap-properties":
  - plugins/postcss-gap-properties/**
  - experimental/postcss-gap-properties/**

"plugins/postcss-global-data":
  - plugins/postcss-global-data/**
  - experimental/postcss-global-data/**

"plugins/postcss-gradients-interpolation-method":
  - plugins/postcss-gradients-interpolation-method/**
  - experimental/postcss-gradients-interpolation-method/**

"plugins/postcss-hwb-function":
  - plugins/postcss-hwb-function/**
  - experimental/postcss-hwb-function/**

"plugins/postcss-ic-unit":
  - plugins/postcss-ic-unit/**
  - experimental/postcss-ic-unit/**

"plugins/postcss-image-set-function":
  - plugins/postcss-image-set-function/**
  - experimental/postcss-image-set-function/**

"plugins/postcss-is-pseudo-class":
  - plugins/postcss-is-pseudo-class/**
  - experimental/postcss-is-pseudo-class/**

"plugins/postcss-lab-function":
  - plugins/postcss-lab-function/**
  - experimental/postcss-lab-function/**

"plugins/postcss-logical":
  - plugins/postcss-logical/**
  - experimental/postcss-logical/**

"plugins/postcss-logical-float-and-clear":
  - plugins/postcss-logical-float-and-clear/**
  - experimental/postcss-logical-float-and-clear/**

"plugins/postcss-logical-resize":
  - plugins/postcss-logical-resize/**
  - experimental/postcss-logical-resize/**

"plugins/postcss-logical-viewport-units":
  - plugins/postcss-logical-viewport-units/**
  - experimental/postcss-logical-viewport-units/**

"plugins/media-queries-aspect-ratio-number-values":
  - plugins/postcss-media-queries-aspect-ratio-number-values/**
  - experimental/postcss-media-queries-aspect-ratio-number-values/**

"plugins/postcss-media-minmax":
  - plugins/postcss-media-minmax/**
  - experimental/postcss-media-minmax/**

"plugins/postcss-nested-calc":
  - plugins/postcss-nested-calc/**
  - experimental/postcss-nested-calc/**

"plugins/postcss-nesting":
  - plugins/postcss-nesting/**
  - experimental/postcss-nesting/**

"plugins/postcss-normalize-display-values":
  - plugins/postcss-normalize-display-values/**
  - experimental/postcss-normalize-display-values/**

"plugins/postcss-oklab-function":
  - plugins/postcss-oklab-function/**
  - experimental/postcss-oklab-function/**

"plugins/postcss-overflow-shorthand":
  - plugins/postcss-overflow-shorthand/**
  - experimental/postcss-overflow-shorthand/**

"plugins/postcss-page-break":
  - plugins/postcss-page-break/**
  - experimental/postcss-page-break/**

"plugins/postcss-place":
  - plugins/postcss-place/**
  - experimental/postcss-place/**

"plugins/postcss-progressive-custom-properties":
  - plugins/postcss-progressive-custom-properties/**
  - experimental/postcss-progressive-custom-properties/**

"plugins/postcss-pseudo-class-any-link":
  - plugins/postcss-pseudo-class-any-link/**
  - experimental/postcss-pseudo-class-any-link/**

"plugins/postcss-relative-color-syntax":
  - plugins/postcss-relative-color-syntax/**
  - experimental/postcss-relative-color-syntax/**

"plugins/postcss-replace-overflow-wrap":
  - plugins/postcss-replace-overflow-wrap/**
  - experimental/postcss-replace-overflow-wrap/**

"plugins/postcss-scope-pseudo-class":
  - plugins/postcss-scope-pseudo-class/**
  - experimental/postcss-scope-pseudo-class/**

"plugins/postcss-selector-not":
  - plugins/postcss-selector-not/**
  - experimental/postcss-selector-not/**

"plugins/postcss-system-ui-font-family":
  - plugins/postcss-system-ui-font-family/**
  - experimental/postcss-system-ui-font-family/**

"plugins/postcss-stepped-value-functions":
  - plugins/postcss-stepped-value-functions/**
  - experimental/postcss-stepped-value-functions/**

"plugins/postcss-text-decoration-shorthand":
  - plugins/postcss-text-decoration-shorthand/**
  - experimental/postcss-text-decoration-shorthand/**

"plugins/postcss-trigonometric-functions":
  - plugins/postcss-trigonometric-functions/**
  - experimental/postcss-trigonometric-functions/**

"plugins/postcss-unset-value":
  - plugins/postcss-unset-value/**
  - experimental/postcss-unset-value/**

"sites/postcss-preset-env":
  - sites/postcss-preset-env/**
