name: '🐞 Unexpected CSS output report'
description: CSS output is unexpected or breaks in certain cases? This is your path!
body:
  - type: markdown
    attributes:
      value:  Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: descr
    attributes:
      label: Bug description
      description: What's the bug?
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: Source CSS
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected CSS
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual CSS
    validations:
      required: true
  - type: textarea
    id: playground_link
    attributes:
      label: Playgound example
      description: If you can recreate your issue in the [playground](https://preset-env.cssdb.org/playground/) you can link to your example here.
  - type: dropdown
    id: npx
    attributes:
      label: Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?
      multiple: false
      options:
        - "Yes"
        - "No"
        - N/A
  - type: textarea
    id: debug
    attributes:
      label: Debug output
      description: If this issue is about `postcss-preset-env`, can you provide the output of using the [debug](https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env#debug) option?
    validations:
      required: false
  - type: textarea
    id: config
    attributes:
      label: Extra config
      description: If you have external plugins and/or config that could be causing this issue to happen we would love to know!
    validations:
      required: false
  - type: dropdown
    id: plugin
    attributes:
      label: What plugin are you experiencing this issue on?
      multiple: true
      options:
        - PostCSS Preset Env
        - PostCSS Bundler
        - CSS Blank Pseudo
        - CSS Has Pseudo
        - CSS Prefers Color Scheme
        - PostCSS Attribute Case Insensitive
        - PostCSS Browser Comments
        - PostCSS Cascade Layers
        - PostCSS Color Function
        - PostCSS Color Functional Notation
        - PostCSS Color Hex Alpha
        - PostCSS Color Mix Function
        - PostCSS Conditional Values
        - PostCSS Content Alt Text
        - PostCSS Contrast Color Functions
        - PostCSS Custom Media Queries
        - PostCSS Custom Properties
        - PostCSS Custom Selectors
        - PostCSS Design Tokens
        - PostCSS Dir Pseudo Class
        - PostCSS Double Position Gradients
        - PostCSS Env Function
        - PostCSS Exponential Functions
        - PostCSS Extract
        - PostCSS Focus Visible
        - PostCSS Focus Within
        - PostCSS Font Variant
        - PostCSS Gamut Mapping
        - PostCSS Gap Properties
        - PostCSS Global Data
        - PostCSS Gradients Interpolation Method
        - PostCSS HWB Function
        - PostCSS IC Unit
        - PostCSS Image Set Function
        - PostCSS Initial
        - PostCSS Is Pseudo Class
        - PostCSS Lab Function
        - PostCSS Light Dark Function
        - PostCSS Logical
        - PostCSS Logical Float and Clear
        - PostCSS Logical Overflow
        - PostCSS Logical Overscroll Behavior
        - PostCSS Logical Resize
        - PostCSS Logical Viewport Units
        - PostCSS Media Queries Aspect-Ratio Number Values
        - PostCSS Media MinMax
        - PostCSS Minify
        - PostCSS Nested Calc
        - PostCSS Nesting
        - PostCSS OKLab Function
        - PostCSS Overflow Shorthand
        - PostCSS Page Break
        - PostCSS Place
        - PostCSS Progressive Custom Properties
        - PostCSS Pseudo Class Any Link
        - PostCSS Random Function
        - PostCSS Rebase URL
        - PostCSS Rewrite URL
        - PostCSS Rebeccapurple
        - PostCSS Relative Color Syntax
        - PostCSS Replace Overflow Wrap
        - PostCSS Scope Pseudo Class
        - PostCSS Selector Not
        - PostCSS Sign Functions
        - PostCSS Slow Plugins
        - PostCSS Stepped Value Functions
        - PostCSS System Ui Font Family
        - PostCSS Text Decoration Shorthand
        - PostCSS Trigonometric Functions
        - PostCSS Unset Value
  - type: input
    id: version
    attributes:
      label: Plugin version
      description: Exact release version or commit hash
      placeholder: e.g 7.0.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS are you experiencing this on?
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
  - type: input
    id: node
    attributes:
      label: Node Version
      description: Version of Node where you're experiencing this issue on
      placeholder: eg 12.0.0
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
          required: true
        - label: Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
          required: true
  - type: checkboxes
    id: pr
    attributes:
      label: Would you like to open a PR for this bug?
      description: Before starting to work on PR it is recommended to get maintainers approval
      options:
        - label: I'm willing to open a PR
          required: false
