name: '💥 Crash report'
description: Create a report for one of the plugins or PostCSS Preset Env with guided questions
body:
  - type: markdown
    attributes:
      value:  Thanks for taking the time to fill out this bug report!
  - type: input
    id: reproduction
    attributes:
      label: Reproduction link
      description: Please provide a link to a repo that can reproduce the problem you ran into or a minimum reproducible case for your issue. These plugins are used in ways we can not always predict and showing us what you did helps us in tracking down any bugs. So anything from a small CSS snippet that leads to unexpected outputs or even a failing (new) test on a PR would be of immense help!
      placeholder: 'https://runkit.com/..'
  - type: textarea
    id: descr
    attributes:
      label: Bug description
      description: What's the bug?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What's happening?
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false
  - type: dropdown
    id: npx
    attributes:
      label: Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?
      multiple: false
      options:
        - "Yes"
        - "No"
        - N/A
  - type: textarea
    id: npx-result
    attributes:
      label: "`npx` Output"
      description: If you could reproduce with `npx`, what's the output?
    validations:
      required: false
  - type: textarea
    id: config
    attributes:
      label: Extra config
      description: If you have external plugins and/or config that could be causing this issue to happen we would love to know!
    validations:
      required: false
  - type: dropdown
    id: plugin
    attributes:
      label: What plugin are you experiencing this issue on?
      multiple: true
      options:
        - PostCSS Preset Env
        - PostCSS Bundler
        - CSS Blank Pseudo
        - CSS Has Pseudo
        - CSS Prefers Color Scheme
        - PostCSS Attribute Case Insensitive
        - PostCSS Browser Comments
        - PostCSS Cascade Layers
        - PostCSS Color Function
        - PostCSS Color Functional Notation
        - PostCSS Color Hex Alpha
        - PostCSS Color Mix Function
        - PostCSS Conditional Values
        - PostCSS Content Alt Text
        - PostCSS Contrast Color Functions
        - PostCSS Custom Media Queries
        - PostCSS Custom Properties
        - PostCSS Custom Selectors
        - PostCSS Design Tokens
        - PostCSS Dir Pseudo Class
        - PostCSS Double Position Gradients
        - PostCSS Env Function
        - PostCSS Exponential Functions
        - PostCSS Extract
        - PostCSS Focus Visible
        - PostCSS Focus Within
        - PostCSS Font Variant
        - PostCSS Gamut Mapping
        - PostCSS Gap Properties
        - PostCSS Global Data
        - PostCSS Gradients Interpolation Method
        - PostCSS HWB Function
        - PostCSS IC Unit
        - PostCSS Image Set Function
        - PostCSS Initial
        - PostCSS Is Pseudo Class
        - PostCSS Lab Function
        - PostCSS Light Dark Function
        - PostCSS Logical
        - PostCSS Logical Float and Clear
        - PostCSS Logical Overflow
        - PostCSS Logical Overscroll Behavior
        - PostCSS Logical Resize
        - PostCSS Logical Viewport Units
        - PostCSS Media Queries Aspect-Ratio Number Values
        - PostCSS Media MinMax
        - PostCSS Minify
        - PostCSS Nested Calc
        - PostCSS Nesting
        - PostCSS OKLab Function
        - PostCSS Overflow Shorthand
        - PostCSS Page Break
        - PostCSS Place
        - PostCSS Progressive Custom Properties
        - PostCSS Pseudo Class Any Link
        - PostCSS Random Function
        - PostCSS Rebase URL
        - PostCSS Rewrite URL
        - PostCSS Rebeccapurple
        - PostCSS Relative Color Syntax
        - PostCSS Replace Overflow Wrap
        - PostCSS Scope Pseudo Class
        - PostCSS Selector Not
        - PostCSS Slow Plugins
        - PostCSS Stepped Value Functions
        - PostCSS System Ui Font Family
        - PostCSS Text Decoration Shorthand
        - PostCSS Trigonometric Functions
        - PostCSS Unset Value
  - type: input
    id: version
    attributes:
      label: Plugin version
      description: Exact release version or commit hash
      placeholder: e.g 7.0.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS are you experiencing this on?
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
  - type: input
    id: node
    attributes:
      label: Node Version
      description: Version of Node where you're experiencing this issue on
      placeholder: eg 12.0.0
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
          required: true
        - label: Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
          required: true
  - type: checkboxes
    id: pr
    attributes:
      label: Would you like to open a PR for this bug?
      description: Before starting to work on PR it is recommended to get maintainers approval
      options:
        - label: I'm willing to open a PR
          required: false
