export const shorthands = new Map([
	[
		"animation",
		[
			"animation-name",
			"animation-duration",
			"animation-timing-function",
			"animation-delay",
			"animation-iteration-count",
			"animation-direction",
			"animation-fill-mode",
			"animation-play-state",
			"animation-timeline",
			"animation-range",
			"animation-trigger",
			"animation-range-start",
			"animation-range-end"
		]
	],
	[
		"animation-range",
		[
			"animation-range-start",
			"animation-range-end"
		]
	],
	[
		"background",
		[
			"background-image",
			"background-position",
			"background-size",
			"background-repeat",
			"background-attachment",
			"background-origin",
			"background-clip",
			"background-color",
			"background-blend-mode",
			"background-repeat-block",
			"background-repeat-inline",
			"background-repeat-x",
			"background-repeat-y",
			"background-position-x",
			"background-position-y",
			"background-position-block",
			"background-position-inline"
		]
	],
	[
		"background-position",
		[
			"background-position-x",
			"background-position-y",
			"background-position-block",
			"background-position-inline"
		]
	],
	[
		"background-repeat",
		[
			"background-repeat-block",
			"background-repeat-inline",
			"background-repeat-x",
			"background-repeat-y"
		]
	],
	[
		"size",
		[
			"block-size",
			"height",
			"inline-size",
			"width"
		]
	],
	[
		"block-step",
		[
			"block-step-size",
			"block-step-insert",
			"block-step-align",
			"block-step-round"
		]
	],
	[
		"border",
		[
			"border-width",
			"border-style",
			"border-color",
			"border-image",
			"border-image-source",
			"border-image-slice",
			"border-image-width",
			"border-image-outset",
			"border-image-repeat",
			"border-block-end-color",
			"border-block-start-color",
			"border-bottom-color",
			"border-top-color",
			"border-right-color",
			"border-left-color",
			"border-inline-end-color",
			"border-inline-start-color",
			"border-block-end-style",
			"border-block-start-style",
			"border-bottom-style",
			"border-inline-end-style",
			"border-inline-start-style",
			"border-left-style",
			"border-right-style",
			"border-top-style",
			"border-block-end-width",
			"border-block-start-width",
			"border-bottom-width",
			"border-inline-end-width",
			"border-inline-start-width",
			"border-left-width",
			"border-right-width",
			"border-top-width"
		]
	],
	[
		"border-block",
		[
			"border-block-start",
			"border-block-end",
			"border-block-end-width",
			"border-block-end-style",
			"border-block-end-color",
			"border-block-start-width",
			"border-block-start-style",
			"border-block-start-color"
		]
	],
	[
		"border-block-clip",
		[
			"border-block-start-clip",
			"border-block-end-clip"
		]
	],
	[
		"border-block-color",
		[
			"border-block-start-color",
			"border-block-end-color"
		]
	],
	[
		"border-block-end",
		[
			"border-block-end-width",
			"border-block-end-style",
			"border-block-end-color"
		]
	],
	[
		"border-clip",
		[
			"border-block-end-clip",
			"border-block-start-clip",
			"border-bottom-clip",
			"border-top-clip",
			"border-right-clip",
			"border-left-clip",
			"border-inline-end-clip",
			"border-inline-start-clip"
		]
	],
	[
		"border-color",
		[
			"border-block-end-color",
			"border-block-start-color",
			"border-bottom-color",
			"border-top-color",
			"border-right-color",
			"border-left-color",
			"border-inline-end-color",
			"border-inline-start-color"
		]
	],
	[
		"border-block-end-radius",
		[
			"border-end-start-radius",
			"border-end-end-radius"
		]
	],
	[
		"border-style",
		[
			"border-block-end-style",
			"border-block-start-style",
			"border-bottom-style",
			"border-inline-end-style",
			"border-inline-start-style",
			"border-left-style",
			"border-right-style",
			"border-top-style"
		]
	],
	[
		"border-width",
		[
			"border-block-end-width",
			"border-block-start-width",
			"border-bottom-width",
			"border-inline-end-width",
			"border-inline-start-width",
			"border-left-width",
			"border-right-width",
			"border-top-width"
		]
	],
	[
		"border-block-start",
		[
			"border-block-start-width",
			"border-block-start-style",
			"border-block-start-color"
		]
	],
	[
		"border-block-start-radius",
		[
			"border-start-start-radius",
			"border-start-end-radius"
		]
	],
	[
		"border-block-style",
		[
			"border-block-start-style",
			"border-block-end-style"
		]
	],
	[
		"border-block-width",
		[
			"border-block-start-width",
			"border-block-end-width"
		]
	],
	[
		"border-bottom",
		[
			"border-bottom-width",
			"border-bottom-style",
			"border-bottom-color"
		]
	],
	[
		"border-radius",
		[
			"border-bottom-left-radius",
			"border-bottom-right-radius",
			"border-end-end-radius",
			"border-end-start-radius",
			"border-top-left-radius",
			"border-top-right-radius",
			"border-start-end-radius",
			"border-start-start-radius"
		]
	],
	[
		"border-bottom-radius",
		[
			"border-bottom-left-radius",
			"border-bottom-right-radius"
		]
	],
	[
		"border-image",
		[
			"border-image-source",
			"border-image-slice",
			"border-image-width",
			"border-image-outset",
			"border-image-repeat"
		]
	],
	[
		"border-inline",
		[
			"border-inline-start",
			"border-inline-end",
			"border-inline-end-width",
			"border-inline-end-style",
			"border-inline-end-color",
			"border-inline-start-width",
			"border-inline-start-style",
			"border-inline-start-color"
		]
	],
	[
		"border-inline-clip",
		[
			"border-inline-start-clip",
			"border-inline-end-clip"
		]
	],
	[
		"border-inline-color",
		[
			"border-inline-start-color",
			"border-inline-end-color"
		]
	],
	[
		"border-inline-end",
		[
			"border-inline-end-width",
			"border-inline-end-style",
			"border-inline-end-color"
		]
	],
	[
		"border-inline-end-radius",
		[
			"border-start-end-radius",
			"border-end-end-radius"
		]
	],
	[
		"border-inline-start",
		[
			"border-inline-start-width",
			"border-inline-start-style",
			"border-inline-start-color"
		]
	],
	[
		"border-inline-start-radius",
		[
			"border-start-start-radius",
			"border-end-start-radius"
		]
	],
	[
		"border-inline-style",
		[
			"border-inline-start-style",
			"border-inline-end-style"
		]
	],
	[
		"border-inline-width",
		[
			"border-inline-start-width",
			"border-inline-end-width"
		]
	],
	[
		"border-left",
		[
			"border-left-width",
			"border-left-style",
			"border-left-color"
		]
	],
	[
		"border-left-radius",
		[
			"border-top-left-radius",
			"border-bottom-left-radius"
		]
	],
	[
		"border-right",
		[
			"border-right-width",
			"border-right-style",
			"border-right-color"
		]
	],
	[
		"border-right-radius",
		[
			"border-top-right-radius",
			"border-bottom-right-radius"
		]
	],
	[
		"border-top",
		[
			"border-top-width",
			"border-top-style",
			"border-top-color"
		]
	],
	[
		"border-top-radius",
		[
			"border-top-left-radius",
			"border-top-right-radius"
		]
	],
	[
		"inset",
		[
			"bottom",
			"top",
			"right",
			"left",
			"inset-block-end",
			"inset-block-start",
			"inset-inline-end",
			"inset-inline-start"
		]
	],
	[
		"box-shadow",
		[
			"box-shadow-color",
			"box-shadow-offset",
			"box-shadow-blur",
			"box-shadow-spread",
			"box-shadow-position"
		]
	],
	[
		"caret",
		[
			"caret-color",
			"caret-animation",
			"caret-shape"
		]
	],
	[
		"color-adjust",
		[
			"print-color-adjust"
		]
	],
	[
		"column-rule",
		[
			"column-rule-width",
			"column-rule-style",
			"column-rule-color"
		]
	],
	[
		"column-rule-inset",
		[
			"column-rule-inset-cap-start",
			"column-rule-inset-cap-end",
			"column-rule-inset-junction-start",
			"column-rule-inset-junction-end"
		]
	],
	[
		"column-rule-inset-cap",
		[
			"column-rule-inset-cap-start",
			"column-rule-inset-cap-end"
		]
	],
	[
		"column-rule-inset-end",
		[
			"column-rule-inset-cap-end",
			"column-rule-inset-junction-end"
		]
	],
	[
		"column-rule-inset-junction",
		[
			"column-rule-inset-junction-start",
			"column-rule-inset-junction-end"
		]
	],
	[
		"column-rule-inset-start",
		[
			"column-rule-inset-cap-start",
			"column-rule-inset-junction-start"
		]
	],
	[
		"columns",
		[
			"column-width",
			"column-count",
			"column-height"
		]
	],
	[
		"contain-intrinsic-size",
		[
			"contain-intrinsic-block-size",
			"contain-intrinsic-height",
			"contain-intrinsic-inline-size",
			"contain-intrinsic-width"
		]
	],
	[
		"container",
		[
			"container-name",
			"container-type"
		]
	],
	[
		"corner",
		[
			"border-radius",
			"corner-shape",
			"corner-bottom-left-shape",
			"corner-bottom-right-shape",
			"corner-end-end-shape",
			"corner-end-start-shape",
			"corner-top-left-shape",
			"corner-top-right-shape",
			"corner-start-end-shape",
			"corner-start-start-shape",
			"border-bottom-left-radius",
			"border-bottom-right-radius",
			"border-end-end-radius",
			"border-end-start-radius",
			"border-top-left-radius",
			"border-top-right-radius",
			"border-start-end-radius",
			"border-start-start-radius"
		]
	],
	[
		"corner-block-end",
		[
			"border-block-end-radius",
			"corner-block-end-shape",
			"corner-end-start-shape",
			"corner-end-end-shape",
			"border-end-start-radius",
			"border-end-end-radius"
		]
	],
	[
		"corner-block-end-shape",
		[
			"corner-end-start-shape",
			"corner-end-end-shape"
		]
	],
	[
		"corner-block-start",
		[
			"border-block-start-radius",
			"corner-block-start-shape",
			"corner-start-start-shape",
			"corner-start-end-shape",
			"border-start-start-radius",
			"border-start-end-radius"
		]
	],
	[
		"corner-block-start-shape",
		[
			"corner-start-start-shape",
			"corner-start-end-shape"
		]
	],
	[
		"corner-bottom",
		[
			"border-bottom-radius",
			"corner-bottom-shape",
			"corner-bottom-left-shape",
			"corner-bottom-right-shape",
			"border-bottom-left-radius",
			"border-bottom-right-radius"
		]
	],
	[
		"corner-bottom-left",
		[
			"border-bottom-left-radius",
			"corner-bottom-left-shape"
		]
	],
	[
		"corner-shape",
		[
			"corner-bottom-left-shape",
			"corner-bottom-right-shape",
			"corner-end-end-shape",
			"corner-end-start-shape",
			"corner-top-left-shape",
			"corner-top-right-shape",
			"corner-start-end-shape",
			"corner-start-start-shape"
		]
	],
	[
		"corner-bottom-right",
		[
			"border-bottom-right-radius",
			"corner-bottom-right-shape"
		]
	],
	[
		"corner-bottom-shape",
		[
			"corner-bottom-left-shape",
			"corner-bottom-right-shape"
		]
	],
	[
		"corner-end-end",
		[
			"border-end-end-radius",
			"corner-end-end-shape"
		]
	],
	[
		"corner-end-start",
		[
			"border-end-start-radius",
			"corner-end-start-shape"
		]
	],
	[
		"corner-inline-end",
		[
			"border-inline-end-radius",
			"corner-inline-end-shape",
			"corner-start-end-shape",
			"corner-end-end-shape",
			"border-start-end-radius",
			"border-end-end-radius"
		]
	],
	[
		"corner-inline-end-shape",
		[
			"corner-start-end-shape",
			"corner-end-end-shape"
		]
	],
	[
		"corner-inline-start",
		[
			"border-inline-start-radius",
			"corner-inline-start-shape",
			"corner-start-start-shape",
			"corner-end-start-shape",
			"border-start-start-radius",
			"border-end-start-radius"
		]
	],
	[
		"corner-inline-start-shape",
		[
			"corner-start-start-shape",
			"corner-end-start-shape"
		]
	],
	[
		"corner-left",
		[
			"border-left-radius",
			"corner-left-shape",
			"corner-top-left-shape",
			"corner-bottom-left-shape",
			"border-top-left-radius",
			"border-bottom-left-radius"
		]
	],
	[
		"corner-left-shape",
		[
			"corner-top-left-shape",
			"corner-bottom-left-shape"
		]
	],
	[
		"corner-right",
		[
			"border-right-radius",
			"corner-right-shape",
			"corner-top-right-shape",
			"corner-bottom-right-shape",
			"border-top-right-radius",
			"border-bottom-right-radius"
		]
	],
	[
		"corner-right-shape",
		[
			"corner-top-right-shape",
			"corner-bottom-right-shape"
		]
	],
	[
		"corner-start-end",
		[
			"border-start-end-radius",
			"corner-start-end-shape"
		]
	],
	[
		"corner-start-start",
		[
			"border-start-start-radius",
			"corner-start-start-shape"
		]
	],
	[
		"corner-top",
		[
			"border-top-radius",
			"corner-top-shape",
			"corner-top-left-shape",
			"corner-top-right-shape",
			"border-top-left-radius",
			"border-top-right-radius"
		]
	],
	[
		"corner-top-left",
		[
			"border-top-left-radius",
			"corner-top-left-shape"
		]
	],
	[
		"corner-top-right",
		[
			"border-top-right-radius",
			"corner-top-right-shape"
		]
	],
	[
		"corner-top-shape",
		[
			"corner-top-left-shape",
			"corner-top-right-shape"
		]
	],
	[
		"cue",
		[
			"cue-before",
			"cue-after"
		]
	],
	[
		"flex",
		[
			"flex-grow",
			"flex-shrink",
			"flex-basis"
		]
	],
	[
		"flex-flow",
		[
			"flex-direction",
			"flex-wrap"
		]
	],
	[
		"font",
		[
			"font-style",
			"font-variant",
			"font-weight",
			"font-stretch",
			"font-size",
			"line-height",
			"font-family",
			"font-feature-settings",
			"font-kerning",
			"font-language-override",
			"font-optical-sizing",
			"font-size-adjust",
			"font-variation-settings",
			"font-variant-ligatures",
			"font-variant-caps",
			"font-variant-alternates",
			"font-variant-numeric",
			"font-variant-east-asian",
			"font-variant-position",
			"font-variant-emoji"
		]
	],
	[
		"font-synthesis",
		[
			"font-synthesis-weight",
			"font-synthesis-style",
			"font-synthesis-small-caps"
		]
	],
	[
		"font-variant",
		[
			"font-variant-ligatures",
			"font-variant-caps",
			"font-variant-alternates",
			"font-variant-numeric",
			"font-variant-east-asian",
			"font-variant-position",
			"font-variant-emoji"
		]
	],
	[
		"gap",
		[
			"row-gap",
			"column-gap"
		]
	],
	[
		"grid",
		[
			"grid-template-rows",
			"grid-template-columns",
			"grid-template-areas",
			"grid-auto-rows",
			"grid-auto-columns",
			"grid-auto-flow"
		]
	],
	[
		"grid-area",
		[
			"grid-row-start",
			"grid-column-start",
			"grid-row-end",
			"grid-column-end"
		]
	],
	[
		"grid-column",
		[
			"grid-column-start",
			"grid-column-end"
		]
	],
	[
		"grid-gap",
		[
			"row-gap",
			"column-gap"
		]
	],
	[
		"grid-row",
		[
			"grid-row-start",
			"grid-row-end"
		]
	],
	[
		"grid-template",
		[
			"grid-template-rows",
			"grid-template-columns",
			"grid-template-areas"
		]
	],
	[
		"inset-block",
		[
			"inset-block-start",
			"inset-block-end"
		]
	],
	[
		"inset-inline",
		[
			"inset-inline-start",
			"inset-inline-end"
		]
	],
	[
		"interest-delay",
		[
			"interest-delay-start",
			"interest-delay-end"
		]
	],
	[
		"line-clamp",
		[
			"max-lines",
			"block-ellipsis",
			"continue"
		]
	],
	[
		"list-style",
		[
			"list-style-type",
			"list-style-position",
			"list-style-image"
		]
	],
	[
		"margin",
		[
			"margin-top",
			"margin-right",
			"margin-bottom",
			"margin-left",
			"margin-block-end",
			"margin-block-start",
			"margin-inline-end",
			"margin-inline-start"
		]
	],
	[
		"margin-block",
		[
			"margin-block-start",
			"margin-block-end"
		]
	],
	[
		"margin-inline",
		[
			"margin-inline-start",
			"margin-inline-end"
		]
	],
	[
		"marker",
		[
			"marker-start",
			"marker-mid",
			"marker-end"
		]
	],
	[
		"mask",
		[
			"mask-image",
			"mask-position",
			"mask-size",
			"mask-repeat",
			"mask-origin",
			"mask-clip",
			"mask-composite",
			"mask-mode",
			"mask-border",
			"mask-border-source",
			"mask-border-slice",
			"mask-border-width",
			"mask-border-outset",
			"mask-border-repeat",
			"mask-border-mode"
		]
	],
	[
		"mask-border",
		[
			"mask-border-source",
			"mask-border-slice",
			"mask-border-width",
			"mask-border-outset",
			"mask-border-repeat",
			"mask-border-mode"
		]
	],
	[
		"max-size",
		[
			"max-block-size",
			"max-height",
			"max-inline-size",
			"max-width"
		]
	],
	[
		"min-size",
		[
			"min-block-size",
			"min-height",
			"min-inline-size",
			"min-width"
		]
	],
	[
		"offset",
		[
			"offset-path",
			"offset-distance",
			"offset-rotate",
			"offset-anchor",
			"offset-position"
		]
	],
	[
		"outline",
		[
			"outline-width",
			"outline-style",
			"outline-color"
		]
	],
	[
		"overflow",
		[
			"overflow-x",
			"overflow-y",
			"overflow-block",
			"overflow-inline"
		]
	],
	[
		"overflow-clip-margin",
		[
			"overflow-clip-margin-top",
			"overflow-clip-margin-right",
			"overflow-clip-margin-bottom",
			"overflow-clip-margin-left",
			"overflow-clip-margin-block-end",
			"overflow-clip-margin-block-start",
			"overflow-clip-margin-inline-end",
			"overflow-clip-margin-inline-start"
		]
	],
	[
		"overflow-clip-margin-block",
		[
			"overflow-clip-margin-block-start",
			"overflow-clip-margin-block-end"
		]
	],
	[
		"overflow-clip-margin-inline",
		[
			"overflow-clip-margin-inline-start",
			"overflow-clip-margin-inline-end"
		]
	],
	[
		"overscroll-behavior",
		[
			"overscroll-behavior-x",
			"overscroll-behavior-y",
			"overscroll-behavior-block",
			"overscroll-behavior-inline"
		]
	],
	[
		"padding",
		[
			"padding-top",
			"padding-right",
			"padding-bottom",
			"padding-left",
			"padding-block-end",
			"padding-block-start",
			"padding-inline-end",
			"padding-inline-start"
		]
	],
	[
		"padding-block",
		[
			"padding-block-start",
			"padding-block-end"
		]
	],
	[
		"padding-inline",
		[
			"padding-inline-start",
			"padding-inline-end"
		]
	],
	[
		"pause",
		[
			"pause-before",
			"pause-after"
		]
	],
	[
		"place-content",
		[
			"align-content",
			"justify-content"
		]
	],
	[
		"place-items",
		[
			"align-items",
			"justify-items"
		]
	],
	[
		"place-self",
		[
			"align-self",
			"justify-self"
		]
	],
	[
		"pointer-timeline",
		[
			"pointer-timeline-name",
			"pointer-timeline-axis"
		]
	],
	[
		"position-try",
		[
			"position-try-order",
			"position-try-fallbacks"
		]
	],
	[
		"rest",
		[
			"rest-before",
			"rest-after"
		]
	],
	[
		"row-rule",
		[
			"row-rule-width",
			"row-rule-style",
			"row-rule-color"
		]
	],
	[
		"row-rule-inset",
		[
			"row-rule-inset-cap-start",
			"row-rule-inset-cap-end",
			"row-rule-inset-junction-start",
			"row-rule-inset-junction-end"
		]
	],
	[
		"row-rule-inset-cap",
		[
			"row-rule-inset-cap-start",
			"row-rule-inset-cap-end"
		]
	],
	[
		"row-rule-inset-end",
		[
			"row-rule-inset-cap-end",
			"row-rule-inset-junction-end"
		]
	],
	[
		"row-rule-inset-junction",
		[
			"row-rule-inset-junction-start",
			"row-rule-inset-junction-end"
		]
	],
	[
		"row-rule-inset-start",
		[
			"row-rule-inset-cap-start",
			"row-rule-inset-junction-start"
		]
	],
	[
		"rule",
		[
			"column-rule",
			"row-rule",
			"row-rule-width",
			"row-rule-style",
			"row-rule-color",
			"column-rule-width",
			"column-rule-style",
			"column-rule-color"
		]
	],
	[
		"rule-break",
		[
			"column-rule-break",
			"row-rule-break"
		]
	],
	[
		"rule-color",
		[
			"column-rule-color",
			"row-rule-color"
		]
	],
	[
		"rule-inset",
		[
			"column-rule-inset",
			"row-rule-inset",
			"row-rule-inset-cap-start",
			"row-rule-inset-cap-end",
			"row-rule-inset-junction-start",
			"row-rule-inset-junction-end",
			"column-rule-inset-cap-start",
			"column-rule-inset-cap-end",
			"column-rule-inset-junction-start",
			"column-rule-inset-junction-end"
		]
	],
	[
		"rule-inset-cap",
		[
			"column-rule-inset-cap",
			"column-rule-inset-cap-start",
			"column-rule-inset-cap-end"
		]
	],
	[
		"rule-inset-end",
		[
			"column-rule-inset-end",
			"row-rule-inset-end",
			"row-rule-inset-cap-end",
			"row-rule-inset-junction-end",
			"column-rule-inset-cap-end",
			"column-rule-inset-junction-end"
		]
	],
	[
		"rule-inset-junction",
		[
			"column-rule-inset-junction",
			"column-rule-inset-junction-start",
			"column-rule-inset-junction-end"
		]
	],
	[
		"rule-inset-start",
		[
			"column-rule-inset-start",
			"row-rule-inset-start",
			"row-rule-inset-cap-start",
			"row-rule-inset-junction-start",
			"column-rule-inset-cap-start",
			"column-rule-inset-junction-start"
		]
	],
	[
		"rule-style",
		[
			"column-rule-style",
			"row-rule-style"
		]
	],
	[
		"rule-visibility-items",
		[
			"column-rule-visibility-items"
		]
	],
	[
		"rule-width",
		[
			"column-rule-width",
			"row-rule-width"
		]
	],
	[
		"scroll-margin",
		[
			"scroll-margin-top",
			"scroll-margin-right",
			"scroll-margin-bottom",
			"scroll-margin-left",
			"scroll-margin-block-end",
			"scroll-margin-block-start",
			"scroll-margin-inline-end",
			"scroll-margin-inline-start"
		]
	],
	[
		"scroll-margin-block",
		[
			"scroll-margin-block-start",
			"scroll-margin-block-end"
		]
	],
	[
		"scroll-margin-inline",
		[
			"scroll-margin-inline-start",
			"scroll-margin-inline-end"
		]
	],
	[
		"scroll-padding",
		[
			"scroll-padding-top",
			"scroll-padding-right",
			"scroll-padding-bottom",
			"scroll-padding-left",
			"scroll-padding-block-end",
			"scroll-padding-block-start",
			"scroll-padding-inline-end",
			"scroll-padding-inline-start"
		]
	],
	[
		"scroll-padding-block",
		[
			"scroll-padding-block-start",
			"scroll-padding-block-end"
		]
	],
	[
		"scroll-padding-inline",
		[
			"scroll-padding-inline-start",
			"scroll-padding-inline-end"
		]
	],
	[
		"scroll-timeline",
		[
			"scroll-timeline-name",
			"scroll-timeline-axis"
		]
	],
	[
		"text-align",
		[
			"text-align-all",
			"text-align-last"
		]
	],
	[
		"text-decoration",
		[
			"text-decoration-line",
			"text-decoration-thickness",
			"text-decoration-style",
			"text-decoration-color"
		]
	],
	[
		"text-decoration-skip",
		[
			"text-decoration-skip-self",
			"text-decoration-skip-box",
			"text-decoration-skip-spaces",
			"text-decoration-skip-ink"
		]
	],
	[
		"text-emphasis",
		[
			"text-emphasis-style",
			"text-emphasis-color"
		]
	],
	[
		"text-spacing",
		[
			"text-spacing-trim",
			"text-autospace"
		]
	],
	[
		"text-wrap",
		[
			"text-wrap-mode",
			"text-wrap-style"
		]
	],
	[
		"timeline-trigger",
		[
			"timeline-trigger-name",
			"timeline-trigger-source",
			"timeline-trigger-activation-range",
			"timeline-trigger-active-range",
			"timeline-trigger-active-range-start",
			"timeline-trigger-active-range-end",
			"timeline-trigger-activation-range-start",
			"timeline-trigger-activation-range-end"
		]
	],
	[
		"timeline-trigger-activation-range",
		[
			"timeline-trigger-activation-range-start",
			"timeline-trigger-activation-range-end"
		]
	],
	[
		"timeline-trigger-active-range",
		[
			"timeline-trigger-active-range-start",
			"timeline-trigger-active-range-end"
		]
	],
	[
		"transition",
		[
			"transition-property",
			"transition-duration",
			"transition-timing-function",
			"transition-delay",
			"transition-behavior"
		]
	],
	[
		"vertical-align",
		[
			"alignment-baseline",
			"baseline-shift",
			"baseline-source"
		]
	],
	[
		"view-timeline",
		[
			"view-timeline-name",
			"view-timeline-axis"
		]
	],
	[
		"white-space",
		[
			"white-space-collapse",
			"text-wrap-mode"
		]
	]
]);
