/**
 * Prefix for every custom property this plugin generates.
 *
 * Generated properties must be recognisable so that they are never processed a
 * second time and never collide with authored custom properties.
 */
const GENERATED_PREFIX = '--_csstools-cf';

/**
 * A custom property that resolves to the guaranteed-invalid value.
 * Used to signal that a call or local variable is invalid at computed-value time.
 */
export const INVALID_IDENT = `${GENERATED_PREFIX}-invalid`;

/**
 * Whether a custom property was generated by this plugin.
 */
export function isGeneratedProperty(prop: string): boolean {
	return prop.startsWith(GENERATED_PREFIX);
}

const sourceHashes = new Map<string, string>();

/**
 * A short, stable hash of the source file, used to avoid collisions between
 * generated names from different stylesheets.
 *
 * This mirrors the naming approach of `postcss-private-rule`.
 */
export function sourceHashFor(from: string | undefined): string {
	if (!from) {
		return '0';
	}

	const existing = sourceHashes.get(from);
	if (existing) {
		return existing;
	}

	const value = hashSourcePath(from);
	sourceHashes.set(from, value);

	return value;
}

/**
 * Hash only the last two path segments, so that names are stable regardless
 * of the absolute location of a project, and avoid `node:crypto` / `node:path`
 * so that this plugin can run in a browser bundle.
 */
function hashSourcePath(from: string): string {
	let hash = 2166136261;
	const source = sourceKey(from);

	for (let i = 0; i < source.length; i++) {
		hash ^= source.charCodeAt(i);
		hash = Math.imul(hash, 16777619);
	}

	return (hash >>> 0).toString(36);
}

function sourceKey(from: string): string {
	const segments = from.replaceAll('\\', '/').split('/').filter((segment) => segment.length > 0);

	if (segments.length === 0) {
		return '.';
	}

	if (segments.length === 1) {
		return `./${segments[0]}`;
	}

	return segments.slice(-2).join('/');
}

/**
 * Builds the custom property names emitted for a single source file.
 *
 * Names embed the source hash so that definitions from different stylesheets
 * can not collide.
 */
export class GeneratedNames {
	private sourceHash: string;

	constructor(sourceHash: string) {
		this.sourceHash = sourceHash;
	}

	argName(id: string, index: number): string {
		return `${GENERATED_PREFIX}-${this.sourceHash}-${id}-arg-${index}`;
	}

	rawName(id: string, index: number): string {
		return `${GENERATED_PREFIX}-${this.sourceHash}-${id}-raw-${index}`;
	}

	localName(id: string, name: string): string {
		return `${GENERATED_PREFIX}-${this.sourceHash}-${id}-local-${name.slice(2)}`;
	}

	resultName(id: string): string {
		return `${GENERATED_PREFIX}-${this.sourceHash}-${id}-result`;
	}
}
