export const externalsForCLI = [
	'fs',
	'path',
	'url',

	'@csstools/postcss-font-format-keywords',
	'@csstools/postcss-hwb-function',
	'@csstools/postcss-is-pseudo-class',
	'@csstools/postcss-normalize-display-values',
	'autoprefixer',
	'browserslist',
	'caniuse-lite',
	'css-blank-pseudo',
	'css-has-pseudo',
	'css-prefers-color-scheme',
	'cssdb',
	'postcss-attribute-case-insensitive',
	'postcss-color-functional-notation',
	'postcss-color-hex-alpha',
	'postcss-color-rebeccapurple',
	'postcss-custom-media',
	'postcss-custom-properties',
	'postcss-custom-selectors',
	'postcss-dir-pseudo-class',
	'postcss-double-position-gradients',
	'postcss-env-function',
	'postcss-focus-visible',
	'postcss-focus-within',
	'postcss-font-variant',
	'postcss-gap-properties',
	'postcss-image-set-function',
	'postcss-initial',
	'postcss-lab-function',
	'postcss-logical',
	'postcss-media-minmax',
	'postcss-nesting',
	'postcss-overflow-shorthand',
	'postcss-page-break',
	'postcss-place',
	'postcss-pseudo-class-any-link',
	'postcss-replace-overflow-wrap',
	'postcss-selector-not',
	'postcss-selector-parser',
	'postcss-value-parser',
	'postcss-values-parser',
];

export const externalsForPlugin = [
	'assert',
	'fs',
	'path',
	'url',

	'postcss',
	/^postcss-\d\.\d$/,
	/^postcss\/lib\/*/,

	'@csstools/postcss-font-format-keywords',
	'@csstools/postcss-hwb-function',
	'@csstools/postcss-is-pseudo-class',
	'@csstools/postcss-normalize-display-values',
	'autoprefixer',
	'browserslist',
	'caniuse-lite',
	'css-blank-pseudo',
	'css-has-pseudo',
	'css-prefers-color-scheme',
	'cssdb',
	'postcss-attribute-case-insensitive',
	'postcss-clamp',
	'postcss-color-functional-notation',
	'postcss-color-hex-alpha',
	'postcss-color-rebeccapurple',
	'postcss-custom-media',
	'postcss-custom-properties',
	'postcss-custom-selectors',
	'postcss-dir-pseudo-class',
	'postcss-double-position-gradients',
	'postcss-env-function',
	'postcss-focus-visible',
	'postcss-focus-within',
	'postcss-font-variant',
	'postcss-gap-properties',
	'postcss-ic-unit',
	'postcss-image-set-function',
	'postcss-initial',
	'postcss-lab-function',
	'postcss-logical',
	'postcss-media-minmax',
	'postcss-nesting',
	'postcss-opacity-percentage',
	'postcss-overflow-shorthand',
	'postcss-page-break',
	'postcss-place',
	'postcss-pseudo-class-any-link',
	'postcss-replace-overflow-wrap',
	'postcss-selector-not',
	'postcss-selector-parser',
	'postcss-value-parser',
	'postcss-values-parser',
];

export const externalsForBrowser = [];

export const externalsForDeno = [];
