name: Pull Request Labeler
on:
  - pull_request_target

defaults:
  run:
    shell: bash

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

