name: Pull Request Labeler
on:
  - pull_request_target

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

